name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-package-deploy:
    runs-on: ubuntu-latest

    env:
      BUILD_DIR: build
      ARTIFACT_NAME: app-binary

    steps:
      - name: Source
        uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir $BUILD_DIR
          gcc main.c -o $BUILD_DIR/$ARTIFACT_NAME

      - name: Test
        run: |
          echo "Running tests"
          test -f $BUILD_DIR/$ARTIFACT_NAME

      - name: Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.BUILD_DIR }}/${{ env.ARTIFACT_NAME }}

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: downloaded

      - name: Simulated Deploy
        env:
          DEPLOY_API_KEY: ${{ secrets.DEPLOY_API_KEY }}
        run: |
          echo "Deploying using artifact:"
          ls downloaded
          echo "Deployment using API Key: $DEPLOY_API_KEY"
